### ISSUE TITLE
Transfering project to Vue3 and Vuex4

### ISSUE THREAD

**Issue by richieracoon** [stagerightlabs/Vue-Three-Demo#4]
I kinda tried to transfer this project to vuex4 and i'm somehow getting the same error over and over: 

Uncaught (in promise) TypeError: 'get' on proxy: property 'modelViewMatrix' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Matrix4>' but got '[object Object]')

Searching for the error has brought me to this post on stackoverflow:
https://stackoverflow.com/questions/65693108/threejs-component-working-in-vuejs-2-but-not-3

But the workaround of course doesnt really mention the usage of vuex which should grant reactivity by itself. 
Can you guess what the issue is?

**Comment by rydurham** [comment]
Very good question.  I have not yet tried porting this project to Vue3 so I have not yet encountered this problem.   If I have a moment I will poke around and see if I can find anything.  Let me know if you figure it out.

**Comment by richieracoon** [comment]
I couldn't fit it into Vuex but there's definitely a workaround I can show you:

<template>
  <div class="simbox">
    <div id="viewport"></div>
  </div>
</template>

<script lang="ts">
import {defineComponent, onMounted, onBeforeUnmount} from 'vue';
import {genSim} from '../threejs/genSim'


export default defineComponent({
  name: 'QuantRegSim',
  props: {
    size: {
      type: Number,
      required: true
    }
  },
  setup() {
    function mountViewer(): void {
      const container: HTMLDivElement = document.getElementById('viewport') as HTMLDivElement;
      genSim(3, container);
    }

    function destroyCanvas(): void {
      const container: HTMLDivElement = document.getElementById('viewport') as HTMLDivElement;
      container.innerHTML = '';
    }

    onMounted(mountViewer);
    onBeforeUnmount(destroyCanvas);

    return {}
  }
});

It is important to set the function that generates the scene onMount and and I could not have done it a different way. Although it is said in the documentation, that if you call the function, in the "return" below it would be executed onMount. Same with the onDestroy. If you don't destroy empty your canvas the scene could be generated twice. 
Finally the three.js code was placed in a seperate TypeScript-File and the function were imported where I needed them in different components. So it's not really incorporated in vuex, but you can still call the functions from anywhere you want to call them.

**Comment by rydurham** [comment]
Take a look at PR #3 - this should hopefully address this request.   I am going to close this issue for now but feel free to reopen if you would like.
